check:
  - thoth-build
build:
  base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.15.0"
  build-stratergy: "Source"
  registry: "quay.io"
  registry-org: "thoth-station"
  registry-project: "si-minimal-notebook"
  registry-secret: "thoth-station-thoth-pusher-secret"
